name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: build dir
      run: mkdir build && cd build
    - name: cmake
      run: cmake --build build && make
    - name: cd build && ctest
      run: ctest -V
